#!/usr/bin/env python
# -*- coding: utf-8 -*-
import pygame
from pygame.locals import (
        K_ESCAPE,
        QUIT,
        KEYDOWN,
)
from player import *

def main():
    pygame.init()
    screen = pygame.display.set_mode((1280,1024), pygame.FULLSCREEN)
    area = pygame.Rect((-1,-1),(1281,1025))
    back = pygame.Surface(screen.get_size())
    back.fill((69,42,128))
    back = back.convert()
    screen.blit(back,(0,0))

    clock = pygame.time.Clock()

    game_loop = True
    player = Player()
    #screen.blit(player.face,player.rec)
    playt = 0.0

    while game_loop:
        milsec = clock.tick(60)
        playt += milsec/1000.0

        for event in pygame.event.get():
            if event.type == QUIT:
                game_loop = False
            elif event.type == KEYDOWN:
                if event.key == K_ESCAPE:
                    game_loop = False

        usr_in = pygame.key.get_pressed()
        player.movement(usr_in)

        screen.blit(player.face,player.rec)
        pygame.display.flip()
        screen.fill((69,42,128))

    pygame.quit()



main()
